#define TRAINER_KYLE 1
#define TRAINER_BILLY 2
#define TRAINER_KEY_LACKEY_FISHEYE_LAKE 3
#define TRAINER_MORGAN_FISHEYE_LAKE 4
#define TRAINER_CALVIN_FISHEYE_LAKE 5

#define FIRST_STARTER_DEPENDENT_INDEX TRAINER_MORGAN_FISHEYE_LAKE

#define STARTER_DEPENDENT_PARTIES_COUNT 2

