#define TRAINER_KYLE 1
#define TRAINER_BOBBY 2
#define TRAINER_KRIS 3
#define TRAINER_WILBUR 4
#define TRAINER_KEY_LACKEY_FISHEYE_LAKE 5
#define TRAINER_MORGAN_FISHEYE_LAKE 6
#define TRAINER_CALVIN_FISHEYE_LAKE 7
#define TRAINER_MORGAN_CLIFF_CLIMB 8

#define FIRST_STARTER_DEPENDENT_INDEX TRAINER_MORGAN_FISHEYE_LAKE

#define STARTER_DEPENDENT_PARTIES_COUNT 3

