// No-difficulty trainers (mooks) 1 - 499
#define TRAINER_KYLE 1
#define TRAINER_BOBBY 2
#define TRAINER_KRIS 3
#define TRAINER_WILBUR 4
#define TRAINER_GRANT 5
#define TRAINER_ROSALYN 6

// Difficulty trainers (mini-bosses / bosses) 500 - 699
#define TRAINER_KEY_LACKEY_FISHEYE_LAKE 500

// Starter-dependent trainers 700-860
#define TRAINER_MORGAN_FISHEYE_LAKE 700
#define TRAINER_CALVIN_FISHEYE_LAKE 701
#define TRAINER_MORGAN_CLIFF_CLIMB 702

#define FIRST_STARTER_DEPENDENT_INDEX TRAINER_MORGAN_FISHEYE_LAKE

#define STARTER_DEPENDENT_PARTIES_COUNT 3

