#ifndef GUARD_CONSTANTS_PORTRAITS_H
#define GUARD_CONSTANTS_PORTRAITS_H

#define PORTRAIT_NONE 							0
#define PORTRAIT_KINGLER_NEUTRAL 				1
#define PORTRAIT_FLYGON_NEUTRAL 				2
#define PORTRAIT_NIDOKING_NEUTRAL 				3
#define PORTRAIT_ZOROARK_NEUTRAL 				4
#define PORTRAIT_AMELIA_NEUTRAL 				5
#define PORTRAIT_AMELIA_SHOCK					6
#define PORTRAITS_COUNT							7

#define PORTRAIT_DEFAULT_X 20
#define PORTRAIT_DEFAULT_Y 5

#endif  // GUARD_CONSTANTS_PORTRAITS_H
