#ifndef GUARD_CONSTANTS_PORTRAITS_H
#define GUARD_CONSTANTS_PORTRAITS_H

#define PORTRAIT_NONE 							0
#define PORTRAIT_KINGLER_NEUTRAL 				1
#define PORTRAIT_KINGLER_LAUGH	 				2
#define PORTRAIT_FLYGON_NEUTRAL 				3
#define PORTRAIT_FLYGON_ANNOYED 				4
#define PORTRAIT_NIDOKING_NEUTRAL 				5
#define PORTRAIT_NIDOKING_NERVOUS 				6
#define PORTRAIT_NIDOKING_GRIN					7
#define PORTRAIT_ZOROARK_NEUTRAL 				8
#define PORTRAIT_AMELIA_NEUTRAL 				9
#define PORTRAIT_AMELIA_SHOCK					10
#define PORTRAIT_AMELIA_ASLEEP					11
#define PORTRAIT_AMELIA_STRAINED				12
#define PORTRAIT_AMELIA_SMUG					13
#define PORTRAIT_AMELIA_SERIOUSLY				14
#define PORTRAIT_AMELIA_WINK					15
#define PORTRAIT_AMELIA_MUNCH					16
#define PORTRAIT_DEMIVEE_NEUTRAL				17
#define PORTRAIT_DEMIVEE_ANNOYED				18
#define PORTRAIT_DEMIVEE_HUH					19
#define PORTRAIT_DEMIVEE_YAY					20
#define PORTRAIT_VINOS_NEUTRAL					21
#define PORTRAIT_VINOS_MAD						22
#define PORTRAIT_KEESIGHT						23
#define PORTRAIT_WEATHERBANE_SCREAM				24
#define PORTRAIT_WEATHERBANE_NEUTRAL			25
#define PORTRAIT_DUBSNAKE_ICE					26
#define PORTRAIT_DUBSNAKE_OIL					27
#define PORTRAIT_HYDROIL_WATER					28
#define PORTRAIT_HYDROIL_FIRE					29
#define PORTRAITS_COUNT							30

#define PORTRAIT_DEFAULT_X 20
#define PORTRAIT_DEFAULT_Y 5
#define PORTRAIT_DEFAULT_LEFT 2, 4, TRUE

#endif  // GUARD_CONSTANTS_PORTRAITS_H
