#ifndef GUARD_CONSTANTS_PORTRAITS_H
#define GUARD_CONSTANTS_PORTRAITS_H

#define PORTRAIT_NONE 							0
#define PORTRAIT_KINGLER_NEUTRAL 				1
#define PORTRAIT_KINGLER_LAUGH	 				2
#define PORTRAIT_FLYGON_NEUTRAL 				3
#define PORTRAIT_FLYGON_ANNOYED 				4
#define PORTRAIT_NIDOKING_NEUTRAL 				5
#define PORTRAIT_NIDOKING_NERVOUS 				6
#define PORTRAIT_ZOROARK_NEUTRAL 				7
#define PORTRAIT_AMELIA_NEUTRAL 				8
#define PORTRAIT_AMELIA_SHOCK					9
#define PORTRAIT_AMELIA_ASLEEP					10
#define PORTRAIT_AMELIA_STRAINED				11
#define PORTRAIT_AMELIA_SMUG					12
#define PORTRAIT_AMELIA_SERIOUSLY				13
#define PORTRAIT_AMELIA_WINK					14
#define PORTRAIT_AMELIA_MUNCH					15
#define PORTRAIT_DEMIVEE_NEUTRAL				16
#define PORTRAIT_DEMIVEE_ANNOYED				17
#define PORTRAIT_DEMIVEE_HUH					18
#define PORTRAIT_DEMIVEE_YAY					19
#define PORTRAIT_VINOS_NEUTRAL					20
#define PORTRAIT_VINOS_MAD						21
#define PORTRAIT_KEESIGHT						22
#define PORTRAITS_COUNT							23

#define PORTRAIT_DEFAULT_X 20
#define PORTRAIT_DEFAULT_Y 5
#define PORTRAIT_DEFAULT_LEFT 2, 4, TRUE

#endif  // GUARD_CONSTANTS_PORTRAITS_H
