LostMansion3_1F_MapScripts::
	.byte 0

LostMansion3_1F_EventScript_TV::
	msgbox LostMansion3_1F_Text_TV, MSGBOX_SIGN
	end
	
LostMansion3_1F_Text_TV:
	.string "A news report...\n"
	.string "The picture's cutting out.\p"
	.string "You can only make out the words\n"
	.string "'FOUND OUTSIDE THE...'$"
	
LostMansion3_1F_EventScript_Psychic::
	msgbox LostMansion3_1F_Text_Psychic, MSGBOX_NPC
	end
	
LostMansion3_1F_Text_Psychic:
	.string "Take a seat!$"
	
	