gText_Birch_Welcome::
	.string "Hey! Glad you finally made it!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is MANGROVE.\p"
	.string "I'm a POKéMON PROFESSOR in the\n"
	.string "FONEI region.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "And this...is a FONEI POKéMON!\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "There are countless varieties\n"
	.string "of POKéMON in this world.\p"
	.string "Some you've never even heard of!\n"
	.string "And neither have I, for that matter.\l"
	.string "FONEI has many wild, untamed places.\p"
	.string "POKéMON lurk in every corner, some\n"
	.string "old and some new.\p"
	.string "Not many people have dared to venture\n"
	.string "into the wild to meet these POKéMON.\p"
	.string "That's my mission: to explore FONEI\n"
	.string "and uncover its secrets!\p"
	.string "Powerful POKéMON, mysterious ruins,\n"
	.string "strange folklore…\l"
	.string "There's so much for me to learn.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And what about you?$"

gText_Birch_BoyOrGirl::
	.string "What do you want to look like?\n"
	.string "$"

gText_Birch_WhatsYourName::
	.string "Alright.\n"
	.string "And what do they call you?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}, is it?$"

gText_Birch_YourePlayer::
	.string "I see!\p"
	.string "So you're {PLAYER}{KUN}, and you want\n"
	.string "to explore FONEI too.\l"
	.string "Who wouldn't?\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Alright, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "My POKéMON LAB is just up the road.\n"
	.string "Come see me when you wake up!\p"
	.string "$"
