gText_Birch_Welcome::
	.string "Urrgghh… where am I?\p"
	.string "I can't seem to remember…\p"
	.string "Who is that man I can remember?\n"
	.string "He seems familiar…\p"
	.string "Who… am I?\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I remember something… a POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "But that POKéMON looks strange.\p"
	.string "I think something very, very odd\n"
	.string "has happened.\p"
	.string "Is it just my memory playing tricks\n"
	.string "on me, or is that POKéMON…\p"
	.string "…dead?\p"
	.string "Surely that can't be right.\n"
	.string "POKéMON don't die when they lose.\l"
	.string "They just faint and can't fight.\p"
	.string "…Right?\n"
	.string "I'm not crazy, am I?\p"
	.string "…wait, I think I remember what\n"
	.string "I look like…\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "I am…?$"

gText_Birch_BoyOrGirl::
	.string "Am I a boy?\n"
	.string "Or am I a girl?$"

gText_Birch_WhatsYourName::
	.string "That's right…\n"
	.string "And my name is…?$"

gText_Birch_SoItsPlayer::
	.string "So I'm {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "At least I remember one thing.\p"
	.string "I'm {PLAYER}{KUN}, and I live in LITTLEROOT\n"
	.string "TOWN. That must be right.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Urrgghh… I think I'm waking up.\p"
	.string "Suddenly, you are lasered by giant\n"
	.string "sharks with laser eyes!\p"
	.string "…no, but seriously, you should leave.\p"
	.string "$"
