gText_Birch_Welcome::
	.string "Welcome to “Recollection Quest”,\n"
	.string "a hack by Sylph.\p"
	.string "This hack was created for the\n"
	.string "Team Aqua's Hideout hack competition\l"
	.string "(sponsored by Team Aqua Asset Repo).\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "In this game, you play as Amelia,\n"
	.string "a seasoned Pokémon Ranger living\l"
	.string "in a far-flung forest far away from\l"
	.string "the regions you know.\p"
	.string "Amelia's Pokémon, Flygon, Kingler,\n"
	.string "Nidoking, and Zoroark, have a long\l"
	.string "history of traveling with her.\p"
	.string "One night, Amelia is separated from\n"
	.string "her team by a flood and washed away\l"
	.string "to an unknown town.\p"
	.string "Using your wits and Amelia's unique\n"
	.string "{EMPHASIS_RED}ability to converse with Pokémon{EMPHASIS_OFF},\l"
	.string "help her recollect her team and\l"
	.string "uncover the truth behind the town's\l"
	.string "endless rainfall…\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
