OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "It's a mad world out there.\n"
	.string "You need to be prepared to take\l"
	.string "whatever you can find.\p"
	.string "It's not stealing if the original\n"
	.string "owner is dead, and keeping yourself\l"
	.string "alive is the most important thing.$"

