OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "What brings you to Cran Town?\n"
	.string "Not many people visit, lately.\p"
	.string "There's not much to do around here,\n"
	.string "But the natural beauty can't be beat.\p"
	.string "Most people just stay in the big city\n"
	.string "up the cliff, though. What a shame.$" 

