CliffEdgeClimbOutside_MapScripts::
	.byte 0

CliffClimbOutside_Sign_1::
	msgbox CliffClimbOutside_Text_Sign1, MSGBOX_SIGN
	end
	
CliffClimbOutside_Text_Sign1:
	.string "{EMPHASIS_RED}CAUTION!{EMPHASIS_OFF}\n"
	.string "Unstable footing! Be careful near\l"
	.string "crumbled edges!\p"
	.string "…spraypainted below, the sign says:\n"
	.string "{EMPHASIS_RED}JUMP OFF! LIVE DANGEROUSLY! ROCK ON!{EMPHASIS_OFF}$"

CliffClimbOutside_Trigger_RivalBattle::
	end
