OldaleTown_House2_MapScripts::
	.byte 0

CranTown_House2_Mother::
	msgbox CranTown_House2_Text_Flash, MSGBOX_NPC
	end

CranTown_House2_Son::
	msgbox CranTown_House2_Text_Swift, MSGBOX_NPC
	end

CranTown_House2_Text_Flash:
	.string "Crafting MOVE MACHINES is a\n"
	.string "family tradition for me and my son.\p"
	.string "Unfortunately, I gave my last HM05\n"
	.string "to a shy girl who came in here\l"
	.string "looking for MANGROVE's lab earlier.\p"
	.string "I'm working on another TM now,\n"
	.string "but it won't be ready for a while.$"

CranTown_House2_Text_Swift:
	.string "My mom taught me how to make\n"
	.string "TECHNICAL MACHINES.\p"
	.string "I made one that teaches SWIFT, but\n"
	.string "I gave it to a goofy haired kid.\p"
	.string "Next time I make one, I'll give it\n"
	.string "to you if you're around.$"

